### PR TITLE
Responsive features: commit again

### PR DESCRIPTION
**Pull request by mutahharaj**
- navigation bar
- adjusted usercard
- adjusted side bar
- adjusted the title popular users for usercard

### CODE REVIEW

**Comment by rishithab48** [comment]
Hi, I checked your branch but I don't see much variation in the normal and mobile versions. Is any of your code missing?

**Comment by rishithab48** [comment]
There are a few errors in your code and I can't run it.
Screenshot 2024-04-16 002754

**Comment by mutahharaj** [comment]
looking into it right now

**Comment by mutahharaj** [comment]
> There are a few errors in your code and I can't run it. Screenshot 2024-04-16 002754

fixed these issues, let me know if you can run it

**Pull request merged**
