### PR TITLE
Registration backend, Author Profile sections

### PR DESCRIPTION
**Pull request by rishithab48**
- Fixed registration backend issues with firebase.
- Created PublishedBooks section for Author profile.
- Fixed a few alignment issues with sampleHome and Footer.

- Fixed Roles Selection bug.

### CODE REVIEW

**Review by mutahharaj — COMMENTED** [review]
the Home, About, and Feed are not displaying on the navigation bar. are they showing up on your end?

**Comment by mutahharaj** [comment]
everything else looks ok

**Comment by rishithab48** [comment]
> the Home, About, and Feed are not displaying on the navigation bar. are they showing up on your end?

Oh yeah, I forgot to fix them. Thanks for reminding me.

**Comment by rishithab48** [comment]
I fixed it now.

**Review by mutahharaj — APPROVED** [review]

**Pull request merged**
