### PR TITLE
General Feed

### LINKED ISSUE #147: [TASK] General Feed Page
### Title

Have a general feed page so non-users can check out the website posts

### Description

- Create a general feed page for non-users.
- It should display the latest feed posts.

### Acceptance criteria

- This page should be accessible on the navigation bar.
- It should have a general display of posts.

### Estimate

3

### Associated feature

#29

### PR DESCRIPTION
**Pull request by racecn**
New:
- firebase admin pkg added, please run npm i 
- admin script to fetch the most popular public posts
    - we can use node-cron later to schedule this
- general feed rendering
- routing to reach general feed

Close #147 General Feed Page

### CODE REVIEW

**Comment by rishithab48** [comment]
Your code looks good but I was wondering if the general feed page is showing latest posts or just some selected ones.

**Comment by rishithab48** [comment]
Also, your branch is 12 commits behind the develop so can you update that?

**Comment by racecn** [comment]
> Also, your branch is 12 commits behind the develop so can you update that?

@rishithab48 being behind should be ok unless  you are working on the same files as someone else -- then you'd have to resolve merge conflicts

**Comment by rishithab48** [comment]
> > Also, your branch is 12 commits behind the develop so can you update that?
> 
> @rishithab48 being behind should be ok unless you are working on the same files as someone else -- then you'd have to resolve merge conflicts

Okay but please make sure that there won't be any conflicts or missing code during your merge.

**Review by rishithab48 — APPROVED** [review]
Looks good to me.

**Pull request merged**
